### ISSUE TITLE
lidarr connection error

### ISSUE THREAD

**Issue by RandomNinjaAtk** [Migz93/lidarr_smloadr_script#20]
Newest version causes a lidarr connection error

![image](https://user-images.githubusercontent.com/8386416/65877152-e9c2dd80-e358-11e9-9cf5-6d0cb77d23ad.png)

I'm not sure what the issue is, reverting to an older version resolved it though... must be something in the last 2 commits...

**Comment by Migz93** [comment]
I had this yesterday while testing and it was me initially leaving one variable as `LidarrApikey` instead of `LidarrApiKey`, i fixed that though.

Have you updated your config variables to be in line with the current config? I tidied up the variable names to have capitlization for each word. Sorry, it's a bit of a pain to change but makes it look cleaner overall as some were all lowercase, some had capitals, and some only had capitals on the last word..

**Comment by RandomNinjaAtk** [comment]
Yes,it was a full download of the script and config file, so I was using the most current version

**Comment by Migz93** [comment]
Ahah okay, thanks for letting me know, i'll have a look straight after work.
If you get a sec could you pastebin your censored config file please, just in case it's a specific option.

May need to go back to having a develop branch and pushing changes there for a test period.

**Comment by RandomNinjaAtk** [comment]
So I think I figured it out and posted a merge request, you didn't update the config sample file with the correct value with the capitalization change. I'm about to re-test it, but that should fix it, since that was likely the issue as you pointed out...

**Comment by RandomNinjaAtk** [comment]
Just tested the pull request change and it seems to have fixed it.

**Comment by Migz93** [comment]
Accepted #21, thanks for that. Unsure how i managed to update it script side after having an error but still missed the config side.
